version: 0.0
os: linux

files:
  - source: target/shopping-mall.jar
    destination: /home/ec2-user/app
    overwrite: yes
  - source: scripts/
    destination: /home/ec2-user/scripts
    overwrite: yes

file_exists_behavior: OVERWRITE

permissions:
  - object: /home/ec2-user/scripts
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755
  - object: /home/ec2-user/app
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 644

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 600
      runas: root
  ApplicationStop:
    - location: scripts/stop_application.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 600
      runas: ec2-user
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 300
      runas: ec2-user
