version: 0.2

phases:
  install:
    commands:
      - echo "Install Maven if needed"
      - if ! command -v mvn >/dev/null 2>&1; then yum -y install maven || (apt-get update && apt-get -y install maven); fi
      - mvn -version || true

  pre_build:
    commands:
      - set -euo pipefail
      - echo "Project tree (top 2 levels)"; find . -maxdepth 2 -print

  build:
    commands:
      - set -e
      - mvn -B -DskipTests -f app/pom.xml clean package
      - JAR_PATH=$(ls -1 app/target/*.jar | grep -v -E '(-sources|-javadoc|-original)\.jar$' | head -n1)
      - echo "JAR=$JAR_PATH"
      - echo "$JAR_PATH" > /tmp/JAR_PATH

  post_build:
    commands:
      - set -e
      - JAR_PATH="$(cat /tmp/JAR_PATH)"
      - mkdir -p artifact/app/build/libs artifact/app/public
      - cp "$JAR_PATH" artifact/app/build/libs/app.jar
      - cp appspec.yml artifact/
      - cp -r scripts systemd artifact/
      - printf '{"commit":"%s","builtAt":"%s"}' "$CODEBUILD_RESOLVED_SOURCE_VERSION" "$(date -u +%FT%TZ)" > artifact/app/public/build.json
      # ===== 디버깅 출력 (매우 중요) =====
      - echo "==== artifact contents ===="
      - find artifact -maxdepth 2 -type f -print
      - echo "==== artifact/appspec.yml ===="
      - sed -n '1,120p' artifact/appspec.yml

artifacts:
  base-directory: artifact
  files:
    - appspec.yml
    - scripts/**/*
    - systemd/**/*
    - app/build/libs/app.jar
    - app/public/build.json
