version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Java installation completed"
      - java -version

  build:
    commands:
      - echo "Starting simple build..."
      - mvn clean package -DskipTests -Dquiet=true
      - echo "Build completed"
      - ls -la target/

artifacts:
  files:
    - target/*.jar
    - appspec.yml
    - scripts/**/*
  base-directory: .
