version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Install Maven if missing"
      - |
        if ! command -v mvn >/dev/null 2>&1; then
          yum -y install maven || (apt-get update && apt-get -y install maven)
        fi
      - mvn -version

  pre_build:
    commands:
      - echo "Use project at ./app (pom.xml here)"
      - echo app > /tmp/PROJECT_DIR

  build:
    commands:
      - |
        set -e
        PROJECT_DIR="$(cat /tmp/PROJECT_DIR)"
        mvn -B -DskipTests -f "$PROJECT_DIR/pom.xml" clean package
        JAR_PATH="$(ls -1 "$PROJECT_DIR/target"/*.jar | grep -v -E '(-sources|-javadoc|-original)\.jar$' | head -n1)"
        [ -n "$JAR_PATH" ] || { echo "JAR not found under $PROJECT_DIR/target"; ls -la "$PROJECT_DIR/target" || true; exit 1; }
        echo "$JAR_PATH" > /tmp/JAR_PATH

  post_build:
    commands:
      - |
        set -e
        JAR_PATH="$(cat /tmp/JAR_PATH)"
        mkdir -p artifact/app/build/libs artifact/app/public
        cp "$JAR_PATH" artifact/app/build/libs/app.jar
        [ -f appspec.yml ] && cp appspec.yml artifact/ || echo "appspec.yml not found (warn)"
        [ -d scripts ] && cp -r scripts artifact/ || echo "scripts/ not found (warn)"
        [ -d systemd ] && cp -r systemd artifact/ || echo "systemd/ not found (warn)"
        printf '{"commit":"%s","builtAt":"%s"}' "$CODEBUILD_RESOLVED_SOURCE_VERSION" "$(date -u +%FT%TZ)" > artifact/app/public/build.json

artifacts:
  files:
    - appspec.yml
    - scripts/**/*
    - systemd/**/*
    - app/build/libs/app.jar
    - app/public/build.json
  base-directory: artifact
