post_build:
  commands:
    - set -e
    - JAR_PATH="$(cat /tmp/JAR_PATH)"
    - mkdir -p artifact/app/build/libs artifact/app/public
    - cp "$JAR_PATH" artifact/app/build/libs/app.jar
    - cp appspec.yml artifact/
    - cp -r scripts artifact/
    - cp -r systemd artifact/
    - printf '{"commit":"%s","builtAt":"%s"}' "$CODEBUILD_RESOLVED_SOURCE_VERSION" "$(date -u +%FT%TZ)" > artifact/app/public/build.json
    # 디버깅: 실제 산출물 내용 확인
    - echo "==== artifact tree ====" && find artifact -maxdepth 2 -type f -print
    - echo "==== artifact/appspec.yml ====" && sed -n '1,120p' artifact/appspec.yml

artifacts:
  base-directory: artifact
  files:
    - appspec.yml
    - scripts/**/*
    - systemd/**/*
    - app/build/libs/app.jar
    - app/public/build.json
