version: 0.2

env:
  variables:
    MAVEN_OPTS: "-Xmx1024m"

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "=== INSTALL PHASE START ==="
      - java -version
      - mvn -version
      - echo "=== INSTALL PHASE COMPLETE ==="

  pre_build:
    commands:
      - echo "=== PRE-BUILD PHASE START ==="
      - echo "Checking project structure..."
      - ls -la
      - echo "=== PRE-BUILD PHASE COMPLETE ==="

  build:
    commands:
      - echo "=== BUILD PHASE START ==="
      - echo "Starting Maven build with timeout..."
      - timeout 600 mvn clean package -DskipTests -Dquiet -B -T 1C || exit 1
      - echo "Checking build output..."
      - ls -la target/
      - echo "=== BUILD PHASE COMPLETE ==="

artifacts:
  files:
    - 'target/*.jar'
    - 'appspec.yml'
    - 'scripts/**/*'
  base-directory: '.'
  name: 'shopping-mall-$(date +%Y-%m-%d)'

cache:
  paths:
    - '/root/.m2/**/*'
