version: 0.2

phases:
  install:
    commands:
      - set -euxo pipefail
      - echo "Install JDK 17 & Maven if needed"
      - yum -y install java-17-amazon-corretto-headless maven || (apt-get update && apt-get -y install openjdk-17-jdk maven)
      - mvn -v || true

  build:
    commands:
      - set -euxo pipefail
      - echo "Detect project dir"
      - |
        PROJECT_DIR="$(dirname "$(find . -type f -name pom.xml | head -n1)")"
        if [ -z "$PROJECT_DIR" ]; then
          echo "No pom.xml found"; echo "== workspace =="; pwd; ls -la; echo "== tree (top) =="; find . -maxdepth 3 -type d -print
          exit 1
        fi
        echo "Building in: $PROJECT_DIR"
        mvn -B -DskipTests -f "$PROJECT_DIR/pom.xml" clean package
        # verify jar exists (for clearer error)
        ls -1 "$PROJECT_DIR/target"/*.jar | head -n1

  post_build:
    commands:
      - set -euxo pipefail
      - echo "Bundle artifacts for CodeDeploy"
      - |
        PROJECT_DIR="$(dirname "$(find . -type f -name pom.xml | head -n1)")"
        [ -n "$PROJECT_DIR" ] || { echo "No pom.xml found in post_build"; exit 1; }
        JAR_PATH="$(ls -1 "$PROJECT_DIR/target"/*.jar | head -n1)"
        [ -n "$JAR_PATH" ] || { echo "JAR not found in post_build"; exit 1; }
        echo "Using JAR: $JAR_PATH"
      - mkdir -p artifact/app/build/libs artifact/app/public
      - cp "$JAR_PATH" artifact/app/build/libs/app.jar
      - cp -r appspec.yml scripts systemd artifact/
      - printf '{"commit":"%s","builtAt":"%s"}' "$CODEBUILD_RESOLVED_SOURCE_VERSION" "$(date -u +%FT%TZ)" > artifact/app/public/build.json

artifacts:
  files:
    - appspec.yml
    - scripts/**/*
    - systemd/**/*
    - app/build/libs/app.jar
    - app/public/build.json
  base-directory: artifact
